#!/bin/bash

ih_path=`dirname "${BASH_SOURCE[0]}"`
if [ -z "${ih_path}" ]; then
	ih_path="."
fi
. "${ih_path}"/ih-functions

show_menu_main() {
	tmp_mselect=`"${DIALOG}" --stdout --clear --title "install-helper" "$@" \
		--menu "Select option:\n\n" 12 51 5 \
		"DiskUtil"  "Disk partitioners." \
		"Install"  "Install system." \
		"Rescue" "Rescue system." \
		"Shell" "Launch a console." \
		"Reboot" "Restart system."`
	retval="${?}"
	echo "${tmp_mselect}"
	return "${retval}"
}

ih_menu_main_select=""
while true; do
	tmp_menu_select=`show_menu_main --default-item "${ih_menu_main_select}"`
	ih_retval="${?}"

	if [ "${ih_retval}" -eq 0 ]; then
		ih_menu_main_select="${tmp_menu_select}"

		case "${ih_menu_main_select}" in
			DiskUtil)
				ih-diskutil
				;;
			Install)
				ih-install
				;;
			Rescue)
				ih-rescue
				;;
			Shell)
				ih-shell
				;;
			Reboot)
				echo b > /proc/sysrq-trigger
				;;
		esac
	fi
done
