#!/bin/bash

. install-helper/ih-functions
. install-helper/ih-diskutil
. install-helper/ih-install
. install-helper/ih-rescue
. install-helper/ih-shell

ih_show_menu_main() {
	tmp_mselect=`"${DIALOG}" --stdout --clear --title "install-helper" "$@" \
		--menu "Select option:\n\n" 14 51 7 \
		"DiskUtil"  "Disk partitioners." \
		"Install"  "Install system." \
		"Rescue" "Rescue system." \
		"GRUB" "GRUB options." \
		"Shell" "Launch a console." \
		"Reboot" "Restart system."`
	retval="${?}"
	echo "${tmp_mselect}"
	return "${retval}"
}

ih_show_menu_main_debug() {
	tmp_mselect=`"${DIALOG}" --stdout --clear --title "install-helper" "$@" \
		--menu "Select option:\n\n" 16 51 9 \
		"DiskUtil"  "Disk partitioners." \
		"Install"  "Install system." \
		"Rescue" "Rescue system." \
		"GRUB" "GRUB options." \
		"Shell" "Launch a console." \
		"Reboot" "Restart system." \
		"BootShell" "Boot /sbin/sh on /rootfsmnt." \
		"BootInit" "Boot /sbin/init on /rootfsmnt."`
	retval="${?}"
	echo "${tmp_mselect}"
	return "${retval}"
}

ih_menu_main_select=""
while true; do
	if [[ "${ih_menu}" == "debug" ]]; then
		tmp_menu_select=`ih_show_menu_main_debug --default-item "${ih_menu_main_select}"`
	else
		tmp_menu_select=`ih_show_menu_main --default-item "${ih_menu_main_select}"`
	fi
	ih_retval="${?}"

	if [ "${ih_retval}" -eq 0 ]; then
		ih_menu_main_select="${tmp_menu_select}"

		case "${ih_menu_main_select}" in
			DiskUtil)
				ih_diskutil
				;;
			Install)
				ih_install
				;;
			Rescue)
				ih_rescue
				if [ $? -eq 0 ]; then
					exit 235
				fi
				;;
			Shell)
				ih_shell
				;;
			Reboot)
				ih_umount_all
				echo b > /proc/sysrq-trigger
				;;
			BootShell)
				exit 234
				;;
			BootInit)
				exit 235
				;;
		esac
	else
		exit 0
	fi
done
