#!/bin/sh

. /scripts/functions

if command -v chvt >/dev/null 2>&1; then
	chvt 1
fi

run_scripts /scripts/panic

# Try to use setsid, which will enable job control in the shell
# and paging in more
if command -v setsid >/dev/null 2>&1; then
	unset IFS
	read -r console rest </proc/consoles
	if [ "${console}" = "tty0" ]; then
		# Need to choose a specific VT
		console="tty1"
	fi
	# We don't have 'setsid -c' so we need to setsid, open
	# the tty, and finally exec an interactive shell
	setsid sh -c "exec ih-main <>/dev/${console} 1>&0 2>&1"
else
	ih-main </dev/console >/dev/console 2>&1
fi
